<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE equipos_de_baloncesto [ 
<!ELEMENT equipos_de_baloncesto (equipo*)>
<!ELEMENT equipo (nombre,ciudad,entrenador,jugadores)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT entrenador (#PCDATA)>
<!ELEMENT jugadores (jugador)>
<!ELEMENT jugador (nombre,posicion,nacionalidad)>
<!ELEMENT posicion (#PCDATA)>
<!ATTLIST posicion nomb (base|escolta|alero|pivot) #REQUIRED>
<!ELEMENT nacionalidad (#PCDATA)>
]>
<equipos_de_baloncesto>
    <equipo>
        <nombre></nombre>
        <ciudad></ciudad>
        <entrenador></entrenador>
        <jugadores>
            <jugador>
                <nombre></nombre>
                <posicion nomb="base"></posicion>
                <nacionalidad></nacionalidad>
            </jugador>
        </jugadores>
    </equipo>
    <equipo>
        <nombre></nombre>
        <ciudad></ciudad>
        <entrenador></entrenador>
        <jugadores>
            <jugador>
                <nombre></nombre>
                <posicion nomb="escolta"></posicion>
                <nacionalidad></nacionalidad>
            </jugador>
        </jugadores>
    </equipo>
</equipos_de_baloncesto>

